name: dav
description: Dart Application Version (DAV) - simple application version display for Dart CLI programs.
version: 0.1.1
repository: https://github.com/wiremoons/dav

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

screenshots:
  - description: 'Dart script version output'
    path: images/dart-aot-exe-version.png
  - description: 'Dart AOT exe version output'
    path: images/dart-script-version.png
