name: dav
description: Dart Application Version (DAV) - simple application version display for Dart CLI programs.
version: 0.1.0
repository: https://github.com/wiremoons/dav

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
